/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Conexion;
import Clases.Ticket;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JC
 */
public class frmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form frmAdministrador
     */
    public frmAdministrador() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarCantidad();

        lblSalirAdm.setOpaque(true);
        Color color = new Color(52, 58, 65);
        lblSalirAdm.setBackground(color);
    }

    public void mostrarDatosTabla(int a) {
        Conexion objConexion = new Conexion();
        // Ticket objTicket = recuperarTicket();

        DefaultTableModel tabla = new DefaultTableModel();

        try {
            tabla.addColumn("Nro Ticket");
            tabla.addColumn("Fecha Registro");
            tabla.addColumn("Solicitante");
            tabla.addColumn("Oficina");
            tabla.addColumn("Cargo");
            tabla.addColumn("Tipo Ticket");
            tabla.addColumn("Asunto");
            tabla.addColumn("Estado");
            tabla.addColumn("Fecha Asignación");
            tabla.addColumn("Prioridad");
            tabla.addColumn("Técnico");
            tabla.addColumn("Fecha Atención");
            //agregar al final nuevas

            //ResultSet rs = objConexion.consultarRegistros("exec usp_bandeja_solitante "+ objTicket.getId_solicitante());
            ResultSet rs = objConexion.consultarRegistros("exec usp_bandeja_administrador " + a);
            
            //
            while (rs.next()) {
                Object dato[] = new Object[12];
                for (int i = 0; i < 12; i++) {
                    dato[i] = rs.getString(i + 1);
                }
                tabla.addRow(dato);
            }
            tblBandeja.setModel(tabla);
        } catch (Exception e) {
        }

    }
    
    public void mostrarCantidad() {
        int r = 0;

        Conexion objConexion = new Conexion();
        try {
            ResultSet rs = objConexion.consultarRegistros("SELECT COUNT(*) "
                    + "AS TOTAL, SUM(CASE WHEN id_estadoTicket=1 THEN 1 ELSE 0 END) "
                    + "AS PENDIENTES_ASIGNACION, SUM(CASE WHEN id_estadoTicket=2 THEN 1 ELSE 0 END) "
                    + "AS PENDIENTES_ATENCION, SUM(CASE WHEN id_estadoTicket IN (3,4) THEN 1 ELSE 0 END) "
                    + "AS ATENDIDOS_OBSERVADOS FROM TB_TICKET WHERE flg_activo=1");
            while (rs.next()) {
               // System.out.println(rs.getString("todos_count"));
                lblTotalTickets.setText(rs.getString("TOTAL"));
                lblPendientesAsig.setText(rs.getString("PENDIENTES_ASIGNACION"));
                lblPendientesAten.setText(rs.getString("PENDIENTES_ATENCION"));
                lblAtendidos.setText(rs.getString("ATENDIDOS_OBSERVADOS"));
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblUsuarioAdm = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPerfilAdm = new javax.swing.JLabel();
        lblTicketAdm = new javax.swing.JLabel();
        lblMantenimientoAdm = new javax.swing.JLabel();
        lblReporteAdm = new javax.swing.JLabel();
        lblSalirAdm = new javax.swing.JLabel();
        lblDerivacion = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNombreAdm = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBandeja = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPendientesAsig = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotalTickets = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPendientesAten = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblAtendidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 232, 232));
        setMinimumSize(new java.awt.Dimension(965, 600));
        setPreferredSize(new java.awt.Dimension(965, 600));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 62, -1, -1));

        jPanel2.setBackground(new java.awt.Color(52, 58, 65));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/adm.png"))); // NOI18N
        jLabel11.setAlignmentY(0.0F);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        lblUsuarioAdm.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblUsuarioAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioAdm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioAdm.setText("Usuario");
        jPanel2.add(lblUsuarioAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 10));

        lblPerfilAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblPerfilAdm.setText("HELPDESK");
        jPanel2.add(lblPerfilAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 140, -1));

        lblTicketAdm.setBackground(new java.awt.Color(72, 78, 83));
        lblTicketAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblTicketAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tk01.png"))); // NOI18N
        lblTicketAdm.setText("Tickets");
        lblTicketAdm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblTicketAdmMouseMoved(evt);
            }
        });
        jPanel2.add(lblTicketAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, 30));

        lblMantenimientoAdm.setBackground(new java.awt.Color(72, 78, 83));
        lblMantenimientoAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblMantenimientoAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tk01.png"))); // NOI18N
        lblMantenimientoAdm.setText("Mantenimiento");
        lblMantenimientoAdm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMantenimientoAdmMouseMoved(evt);
            }
        });
        jPanel2.add(lblMantenimientoAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 140, 30));

        lblReporteAdm.setBackground(new java.awt.Color(72, 78, 83));
        lblReporteAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblReporteAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tk01.png"))); // NOI18N
        lblReporteAdm.setText("Reportes");
        lblReporteAdm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblReporteAdmMouseMoved(evt);
            }
        });
        jPanel2.add(lblReporteAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 140, 30));

        lblSalirAdm.setBackground(new java.awt.Color(52, 58, 65));
        lblSalirAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblSalirAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tk01.png"))); // NOI18N
        lblSalirAdm.setText("Salir");
        lblSalirAdm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSalirAdmMouseMoved(evt);
            }
        });
        lblSalirAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirAdmMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirAdmMouseExited(evt);
            }
        });
        jPanel2.add(lblSalirAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 140, 30));

        lblDerivacion.setBackground(new java.awt.Color(52, 58, 65));
        lblDerivacion.setForeground(new java.awt.Color(255, 255, 255));
        lblDerivacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tk01.png"))); // NOI18N
        lblDerivacion.setText("Derivación");
        lblDerivacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDerivacionMouseMoved(evt);
            }
        });
        lblDerivacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDerivacionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDerivacionMouseExited(evt);
            }
        });
        jPanel2.add(lblDerivacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 140, 520));

        jPanel3.setBackground(new java.awt.Color(60, 141, 187));
        jPanel3.setMinimumSize(new java.awt.Dimension(324, 170));
        jPanel3.setPreferredSize(new java.awt.Dimension(324, 170));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        jPanel4.setBackground(new java.awt.Color(60, 141, 187));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Panel de Administrador");

        lblNombreAdm.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblNombreAdm.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAdm.setText("Nombre");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/adm_ic.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblNombreAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblNombreAdm)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 810, 40));

        jPanel6.setBackground(new java.awt.Color(232, 232, 232));
        jPanel6.setMinimumSize(new java.awt.Dimension(810, 387));
        jPanel6.setPreferredSize(new java.awt.Dimension(810, 387));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBandeja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBandeja);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 790, 270));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BANDEJA DE TICKETS");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 810, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 810, 400));

        jPanel10.setMinimumSize(new java.awt.Dimension(800, 100));
        jPanel10.setPreferredSize(new java.awt.Dimension(800, 100));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(221, 77, 55));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bj.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 74, 51));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pendiente de");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Asignación");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        lblPendientesAsig.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPendientesAsig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendientesAsig.setText("05");
        jPanel8.add(lblPendientesAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, -1));

        jPanel10.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 190, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(1, 109, 246));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bj.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 74, 51));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total tickets");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, -1));

        lblTotalTickets.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalTickets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalTickets.setText("23");
        jPanel5.add(lblTotalTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, -1));

        jPanel10.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 190, 60));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(243, 157, 15));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bj.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 74, 51));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pendientes de");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Atención");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, -1));

        lblPendientesAten.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPendientesAten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendientesAten.setText("00");
        jPanel9.add(lblPendientesAten, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, -1));

        jPanel10.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 190, 60));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 192, 241));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bj.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 74, 51));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Atendidos");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, -1));

        lblAtendidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAtendidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAtendidos.setText("08");
        jPanel7.add(lblAtendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, -1));

        jPanel10.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 190, 60));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 810, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirAdmMouseClicked
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_lblSalirAdmMouseClicked

    private void lblSalirAdmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirAdmMouseExited
        // TODO add your handling code here:

        //  jLabel2.setBackground(Color.red);

    }//GEN-LAST:event_lblSalirAdmMouseExited

    private void lblSalirAdmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirAdmMouseMoved
        // TODO add your handling code here:

        lblSalirAdm.setOpaque(true);
        Color color = new Color(60, 141, 187);
        lblSalirAdm.setBackground(color);

    }//GEN-LAST:event_lblSalirAdmMouseMoved

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        // TODO add your handling code here:

        lblSalirAdm.setOpaque(true);
        Color color = new Color(52, 58, 65);
        lblSalirAdm.setBackground(color);
        lblReporteAdm.setBackground(color);
        lblMantenimientoAdm.setBackground(color);
        lblTicketAdm.setBackground(color);
        lblDerivacion.setBackground(color);

    }//GEN-LAST:event_jPanel2MouseMoved

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:


    }//GEN-LAST:event_jPanel2MouseExited

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:

//       jLabel2.setOpaque(true);
//       Color color=new Color(52,58,65);
//       jLabel2.setBackground(color);

    }//GEN-LAST:event_formMouseMoved

    private void lblReporteAdmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReporteAdmMouseMoved
        // TODO add your handling code here:

        lblReporteAdm.setOpaque(true);
        Color color = new Color(60, 141, 187);
        lblReporteAdm.setBackground(color);

    }//GEN-LAST:event_lblReporteAdmMouseMoved

    private void lblMantenimientoAdmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMantenimientoAdmMouseMoved
        // TODO add your handling code here:
        lblMantenimientoAdm.setOpaque(true);
        Color color = new Color(60, 141, 187);
        lblMantenimientoAdm.setBackground(color);

    }//GEN-LAST:event_lblMantenimientoAdmMouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        mostrarDatosTabla(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblTicketAdmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTicketAdmMouseMoved
        // TODO add your handling code here:

        lblTicketAdm.setOpaque(true);
        Color color = new Color(60, 141, 187);
        lblTicketAdm.setBackground(color);

    }//GEN-LAST:event_lblTicketAdmMouseMoved

    private void lblDerivacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDerivacionMouseMoved
        // TODO add your handling code here:
        lblDerivacion.setOpaque(true);
        Color color = new Color(60, 141, 187);
        lblDerivacion.setBackground(color);

    }//GEN-LAST:event_lblDerivacionMouseMoved

    private void lblDerivacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDerivacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDerivacionMouseClicked

    private void lblDerivacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDerivacionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDerivacionMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         mostrarDatosTabla(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         mostrarDatosTabla(2);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         mostrarDatosTabla(3);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAtendidos;
    private javax.swing.JLabel lblDerivacion;
    private javax.swing.JLabel lblMantenimientoAdm;
    public javax.swing.JLabel lblNombreAdm;
    private javax.swing.JLabel lblPendientesAsig;
    private javax.swing.JLabel lblPendientesAten;
    public javax.swing.JLabel lblPerfilAdm;
    private javax.swing.JLabel lblReporteAdm;
    private javax.swing.JLabel lblSalirAdm;
    private javax.swing.JLabel lblTicketAdm;
    private javax.swing.JLabel lblTotalTickets;
    public javax.swing.JLabel lblUsuarioAdm;
    private javax.swing.JTable tblBandeja;
    // End of variables declaration//GEN-END:variables
}
