/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//https://www.youtube.com/watch?v=qmdL49YMksE
package Formularios;

import Clases.Conexion;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//mssql-jbdc
public class frmLogin2 extends javax.swing.JFrame {

        public String prid;
       // public String prid2;
        
    /**
     * Creates new form frmLogin2
     */
    public frmLogin2() {
        initComponents();
        
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agricultura = new javax.swing.JLabel();
        inia = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agricultura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agricultura.png"))); // NOI18N
        agricultura.setMaximumSize(new java.awt.Dimension(500, 153));
        agricultura.setMinimumSize(new java.awt.Dimension(500, 153));
        agricultura.setPreferredSize(new java.awt.Dimension(500, 153));
        getContentPane().add(agricultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 740, 150));

        inia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inia.png"))); // NOI18N
        getContentPane().add(inia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 260, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/izq.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 200, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Usuario :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 200, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(204, 51, 0));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 160, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText("INICIAR SESIÓN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel5.setText("________________________________________");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 200, -1));

        jLabel6.setText("________________________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Universidad Tecnológica del Perú");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        
        String usuario=txtUsuario.getText();
        String password=txtPassword.getText();
        
        Conexion objConexion=new Conexion();
            
        try {
            //ResultSet rs = st.executeQuery("select ds_login, ds_clave, id_perfil from TB_USUARIO where flg_activo=1 and ds_login='"+ usuario +"'");
            
//            ResultSet rs = st.executeQuery("SELECT TB_USUARIO.ds_login, TB_USUARIO.ds_clave, TB_USUARIO.id_perfil, TB_PERSONA.ds_nroDocumento, TB_PERSONA.ds_nombre, TB_OFICINA.ds_oficina, TB_CARGO.ds_cargo"
//                    + " from TB_USUARIO INNER JOIN TB_PERSONA on TB_USUARIO.id_persona = TB_PERSONA.id_persona"
//                    + " INNER JOIN TB_CARGO on TB_CARGO.id_cargo = TB_PERSONA.id_cargo"
//                    + " INNER JOIN TB_OFICINA on TB_OFICINA.id_oficina = TB_PERSONA.id_oficina"
//                    + " where tb_usuario.flg_activo=1 and TB_USUARIO.ds_login='"+ usuario +"'");
               //ID p: 1 : ADM   2:OP    3: TEC
               ResultSet rs = objConexion.consultarRegistros("exec usp_login_usuario '"+usuario+"'");   
            
            if (rs.next()) {
                    //si existe el usuario
//                   String u=rs.getString("ds_login");
//                   String p=rs.getString("ds_clave");
                     prid=rs.getString("id_persona");
                     
                     String us=rs.getString("ds_login");
                     
                    // prid2 =rs.getString("id_persona");
                     
                     String p=rs.getString("ds_clave");
                     String pf=rs.getString("id_perfil");
                     String n=rs.getString("ds_nombre");
                     String paterno=rs.getString("ds_apPaterno");
                     String materno=rs.getString("ds_apMaterno");
                     String telefono=rs.getString("ds_correo");
                     String correo=rs.getString("ds_telefono");
                     String DNI=rs.getString("ds_nroDocumento");
                     String oficina=rs.getString("ds_oficina");
                     String cargo=rs.getString("ds_cargo");


                   if (password.equals(p)) {
                       //vamos al formulario q corresponde
                       
                       if (pf.equals("1")) {
                           
                           frmUsuario Usuario = new frmUsuario();
                           //frmRegistroTicket RegistroTicket = new frmRegistroTicket();
                           
                           Usuario.setVisible(true);
                           this.setVisible(false);
                           
                           Usuario.lblNombreOperador.setText(" "+n+" "+paterno+"");
                           Usuario.lblIdPersona.setText(prid);
                           //Usuario.texto.setText(prid);
                           
                           Usuario.lblUsuarioUser.setText(us);
                                                      
                           Usuario.lblApellidos.setText(" "+paterno+" "+materno+"");;
                           
                        //   frmRegistraIncidencia.lblUsuario.setText(prid2);
                           
                           Usuario.lblDNI.setText(DNI);
                           Usuario.lblNombre.setText(n);
                           
                           Usuario.lblTelefono.setText(telefono);
                           Usuario.lblCorreo.setText(correo);
                           Usuario.lblOficina.setText(oficina);
                           Usuario.lblCargo.setText(cargo);
                           
                       }else if(pf.equals("2")) {
                            frmAdministrador Administrador=new frmAdministrador();
                           Administrador.setVisible(true);
                          // frmRegistraTicket.lblIdPersona.setText(prid);
                           //Administrador.lblNombreAdm.setText(n);
                           Administrador.lblNombreAdm.setText(" "+n+" "+paterno+"");
                           Administrador.lblUsuarioAdm.setText(us);
                           
                           this.setVisible(false);
                       }else if(pf.equals("3")) {
                            
                           frmTecnico Tecnico = new frmTecnico();
                           Tecnico.setVisible(true);
                           this.setVisible(false);
                           
                           
                           Tecnico.lblIdPersona.setText(prid);
                       }
                    
                    }else{
                     JOptionPane.showMessageDialog(null, "La contraseña no es correcta");  
                   }
                   
            }
            else {
                // el usuario no existe
                JOptionPane.showMessageDialog(null, "El usuario no existe en la BD");
            }
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
        
                
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agricultura;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel inia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
